- project:
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - virtualbmc-tempest-ironic
        - virtualbmc-tox-codespell:
            voting: false
    gate:
      jobs:
        - virtualbmc-tempest-ironic
